format = """$os$username$hostname$kubernetes$directory$git_branch$git_status$nodejs$battery"""

[line_break]
disabled = true

[character]
success_symbol = ''
error_symbol = ''

[os]
format = '[$symbol](bold white) '   
disabled = true

[os.symbols]
Windows = ' '
Ubuntu = ''
Macos = '󰀵'

[username]
style_user = 'green bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '@[$hostname](bold green)'
disabled = false

[directory]
truncation_length = 1
truncation_symbol = '…/'
read_only_style = '196'
read_only = '  '
format = ' [$path](bold blue)[$read_only]($read_only_style) '

[git_branch]
format = '[$symbol]($style)[$branch]($style) '
# truncation_length = 4
truncation_symbol = '…/'

# [git_status]
# format = '([ \($all_status$ahead_behind\)]($style) )'

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[nodejs]
symbol = "[⬢](bold green) "
format = '[$symbol]($style)[$version]($style) '
