format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_status\
$package\
$nodejs\
$python\
$lua\
$docker_context\
$golang\
$deno\
$bun\
$zig\
$conda\
$shell\
$battery
"""

[line_break]
disabled = true

[character]
success_symbol = ''
error_symbol = ''

[username]
style_user = 'green bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '@[$hostname](bold green)'
disabled = false

[directory]
truncation_symbol = '…/'
read_only_style = '196'
read_only = '  '
format = ' [$path](bold blue)[$read_only]($read_only_style) '

[git_branch]
format = '[$symbol]($style)[$branch]($style) '
truncation_symbol = '…/'

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[nodejs]
symbol = "[⬢](bold green) "
format = '[$symbol]($style)[$version]($style) '

[package]
format = '[$symbol]($style)[$version]($style) '

[shell]
zsh_indicator = '%'
disabled = false
